name: Crypto Predictions (5-min Cron)

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Clear previous models
      run: |
        mkdir -p ./models
        rm -rf ./models/*  # Force-clear the directory
        echo "Models directory cleaned"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate new predictions
      run: python crypto_predictor.py
    
    - name: Commit and push updates
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add ./models/
        git diff --cached --quiet || git commit -m "[Auto] Update models/predictions - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
