name: Crypto Predictions (5-min Cron)

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Clear previous model files
      run: |
        # Only delete contents (keep folder structure)
        find ./models -mindepth 1 -delete
        echo "Previous model files cleared (kept ./models directory)"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate new predictions
      run: python crypto_model_training.py  # Updated script name
    
    - name: Commit and push updates
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add ./models/
        if [ -n "$(git status --porcelain ./models)" ]; then
          git commit -m "[Auto] Updated models/predictions $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
